### ISSUE TITLE
communicate just with two phones

### ISSUE THREAD

**Issue by jeremielodi** [ksenia312/nearby_service#3] opened 2024-04-08 09:45 UTC
Hello @ksenia312 !
Good job! this works perfectly on my android phone and it's easy to integrate to other flutter applications.
My test for this nearby service worked only in the case I have 3 phones, the first create an hotspot and the two others connect to it and start sharing files..

Is it possible to use just two phones where the first create an hotspot and the second connect ?

Thanks,

**Comment by ksenia312** [comment] 2024-04-09 18:13
Hello @jeremielodi !

Yes, the plugin works for only 2 devices. Both of them must have Wi-Fi enabled in the settings (no connection is required, just the enabled setting). And enabled hotspot is not needed for plugin to work. In README.md at the very end there is a video of the operation for two phones for Android and IOS.

If you encounter any specific error when working with 2 devices, please write here.

**Comment by jeremielodi** [comment] 2024-04-16 13:12
I don't know if I can call this an issue, but when a phone try to discover peers, it get all the devices around in those whitch are not in the same network with it, the if the list is long the phone you want to communicate with doesn’t appears.

**Comment by ksenia312** [comment] 2024-04-17 07:58
> I don't know if I can call this an issue, but when a phone try to discover peers, it get all the devices around in those whitch are not in the same network with it, the if the list is long the phone you want to communicate with doesn’t appears.
Hello @jeremielodi 
In the context of a p2p network, the concept of "on the same network" is not usually used. Devices don't use a regular local or wide area network to connect, they create their own. That is, your phone finds all available devices that are visible to Wi-Fi Direct within a radius of your location. 
Which devices are visible to you comes from the native wifi.p2p plugin and we cannot control them

**Comment by ksenia312** [comment] 2024-04-17 08:27
> Hello @ksenia312 !
> Is it possible to check in the this library if we can catch the case the discover() function return false.
> I ran into an issue, One of my phones refuse to discovers peers suddenly, I was working before.

Got it, I'll make an update - I'll output the error logs from Android. Thanks for noticing, I didn't realize that at all!
But please note that errors in Android will be in error codes format. I'll try to do my best to make it clearer what happened, but they may still not accurately reflect the cause

In your case, make sure you have location and Wi-fi enabled on your phone, they are most often the cause of discover() crashing

**Comment by jeremielodi** [comment] 2024-04-17 11:38
Great, looking forward for the update, thank you for the fabulous job you are doing.

**Comment by ksenia312** [comment] 2024-04-21 08:40
> Hello @ksenia312 ! Is it possible to check in the this library if we can catch the case the discover() function return false. I ran into an issue, One of my phones refuse to discovers peers suddenly, It was working before.
> 
> <img alt="discover" width="530" src="https://private-user-images.githubusercontent.com/25838121/322873728-87929701-b0d4-4dec-a199-ee86e2553353.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODg4NjIsIm5iZiI6MTcxMzY4ODU2MiwicGF0aCI6Ii8yNTgzODEyMS8zMjI4NzM3MjgtODc5Mjk3MDEtYjBkNC00ZGVjLWExOTktZWU4NmUyNTUzMzUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA4MzYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5OTBlMGU5YWY1YzQzYTJkN2VkOGUwMDEzMjQ4YzQ0NmEwYjlkNTdlYWU2ZmVmNmU3NWQ0ZDVhNTkwOWU0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s3DgqTLz9JMUM5Fu9LOMyMDtTQYPief5gD-xoTdSk7M">
> if the result is false, there is no way to figure out why
> 
> <img alt="Screenshot 2024-04-16 at 14 46 41" width="825" src="https://private-user-images.githubusercontent.com/25838121/322873755-8ec5aa21-95aa-46d1-bfbf-0cf20268aec1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODg4NjIsIm5iZiI6MTcxMzY4ODU2MiwicGF0aCI6Ii8yNTgzODEyMS8zMjI4NzM3NTUtOGVjNWFhMjEtOTVhYS00NmQxLWJmYmYtMGNmMjAyNjhhZWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA4MzYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MzQzMDBiMGExNWZlODJhZWUyNDYwMDNkMWZhYThkYWZiN2ZhNjgyZDY3MTJiNGE1NjIyZjMxZTAwNmM1NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.klwJv9iS14_9HjwC6MX5Vr0BtrZUa7A9JUkg0DqoBqQ">

Hello, I have moved this comment to a separate issue to clearly display the problem for the rest of the users #4 
This discussion will be closed

**Closed by ksenia312** 2024-04-21 08:40 UTC
